# Generated by Django 6.0.5 on 2026-05-15 06:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import literature.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('member', '普通成员')], default='member', max_length=10, verbose_name='用户角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所属部门')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='literature_user_set', related_query_name='literature_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='literature_user_set', related_query_name='literature_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='文献标题')),
                ('authors', models.CharField(blank=True, max_length=500, verbose_name='作者')),
                ('journal', models.CharField(blank=True, max_length=200, verbose_name='期刊/会议')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='发表年份')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='关键词')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('file', models.FileField(help_text='仅支持PDF格式，最大50MB', upload_to=literature.models.literature_file_path, verbose_name='PDF文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='文件MD5哈希')),
                ('presenter', models.CharField(blank=True, max_length=100, verbose_name='分享人')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='组会日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literatures', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文献',
                'verbose_name_plural': '文献',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('upload', '上传文献'), ('download', '下载文献'), ('update', '更新文献'), ('delete', '删除文献'), ('check', '查重'), ('user_create', '创建用户'), ('user_update', '更新用户'), ('user_delete', '删除用户'), ('settings_change', '修改设置')], max_length=20, verbose_name='操作类型')),
                ('target', models.CharField(blank=True, max_length=500, verbose_name='操作对象')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='对象ID')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待检测'), ('processing', '检测中'), ('completed', '已完成'), ('failed', '检测失败')], default='pending', max_length=20, verbose_name='检测状态')),
                ('similarity_score', models.FloatField(blank=True, null=True, verbose_name='相似度')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='是否重复')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='详细结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='外部检测ID')),
                ('api_provider', models.CharField(blank=True, max_length=50, verbose_name='API提供商')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_checks', to='literature.literature', verbose_name='文献')),
            ],
            options={
                'verbose_name': '查重记录',
                'verbose_name_plural': '查重记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(max_length=500, verbose_name='来源文献标题')),
                ('source_authors', models.CharField(blank=True, max_length=500, verbose_name='来源作者')),
                ('source_url', models.URLField(blank=True, verbose_name='来源链接')),
                ('similarity', models.FloatField(verbose_name='相似度')),
                ('matched_content', models.TextField(blank=True, verbose_name='匹配内容')),
                ('matched_literature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_as_duplicate', to='literature.literature', verbose_name='匹配的内部文献')),
                ('plagiarism_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_sources', to='literature.plagiarismcheck', verbose_name='查重记录')),
            ],
            options={
                'verbose_name': '重复来源',
                'verbose_name_plural': '重复来源',
                'ordering': ['-similarity'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='设置键')),
                ('value', models.TextField(verbose_name='设置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
        migrations.AddIndex(
            model_name='literature',
            index=models.Index(fields=['title'], name='literature__title_82e7de_idx'),
        ),
        migrations.AddIndex(
            model_name='literature',
            index=models.Index(fields=['authors'], name='literature__authors_43b6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='literature',
            index=models.Index(fields=['year'], name='literature__year_c12522_idx'),
        ),
        migrations.AddIndex(
            model_name='literature',
            index=models.Index(fields=['uploader'], name='literature__uploade_4d5a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='literature',
            index=models.Index(fields=['created_at'], name='literature__created_0cbac0_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['user'], name='literature__user_id_4d6dee_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['action'], name='literature__action_6897f5_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['created_at'], name='literature__created_c7dae9_idx'),
        ),
    ]
